# Dockerfile for tdproj/vittlerdev

FROM proj/ionic

LABEL description="Ionic" \
      version="1.0" \
      maintainer="dom@dominikdev.com"

ADD init-or-start-ion-app.sh /usr/local/bin/
CMD bash -C '/usr/local/bin/init-or-start-ion-app.sh';'bash'
